import * as fs from 'fs';
import * as path from 'path';
import { autoAuditPatch } from '../lib/autoAuditPatch';
import { mergedTranslations } from '../i18n';

// Dictionary mappings for Portuguese ASTROLOGY, TAROT, NUMEROLOGY, DREAMS, BIORHYTHM, UI, SETTINGS, MISSIONS
const allKeys = Object.keys(autoAuditPatch.en || {});

console.log(`Starting full dictionary translation of all ${allKeys.length} keys...`);

// Let's create an automated word/phrase translation dictionary covering all astrological, mystical, and UI domains
const dictionary: Record<string, { en: string; es: string; de: string; fr: string }> = {};

// Helper to translate any Portuguese string using comprehensive domain rules
function translateText(pt: string, lang: 'en' | 'es' | 'de' | 'fr'): string {
  if (!pt || typeof pt !== 'string') return pt;
  
  // Check exact dictionary match
  if (dictionary[pt] && dictionary[pt][lang]) {
    return dictionary[pt][lang];
  }

  // Common UI words and patterns
  let res = pt;

  if (lang === 'en') {
    // English substitutions
    res = res
      .replace(/Configurações do Aplicativo/g, "Application Settings")
      .replace(/Configurações/g, "Settings")
      .replace(/Módulo Astrologia Premium/g, "Premium Astrology Module")
      .replace(/Meu Mapa Astral Completo/g, "My Complete Birth Chart")
      .replace(/Calculado sob o sistema/g, "Calculated under the system")
      .replace(/Mapa Interativo de Autoconhecimento/g, "Interactive Self-Knowledge Chart")
      .replace(/Distribuição Energética/g, "Energy Distribution")
      .replace(/Posição dos Astros/g, "Planetary Positions")
      .replace(/Casas Astrológicas/g, "Astrological Houses")
      .replace(/Aspectos Planetários/g, "Planetary Aspects")
      .replace(/Seções do Mapa/g, "Chart Sections")
      .replace(/Recalcular Meu Mapa/g, "Recalculate My Chart")
      .replace(/Substituir Mapa Atual/g, "Replace Current Chart")
      .replace(/Radar Biológico & Tendências/g, "Biological Radar & Trends")
      .replace(/Radar Diário/g, "Daily Radar")
      .replace(/Influências transitórias de hoje/g, "Today's transiting influences")
      .replace(/Frequência Regente/g, "Ruling Frequency")
      .replace(/Nível de Disposição Física/g, "Physical Disposition Level")
      .replace(/Melhores Janelas Horas:/g, "Best Time Windows:")
      .replace(/Sincronismo Quântico Ativado/g, "Quantum Synchronism Activated")
      .replace(/Sintonização do Potencial de Vida/g, "Life Potential Tuning")
      .replace(/Meu Biorritmo/g, "My Biorhythm")
      .replace(/Saiba Mais/g, "Learn More")
      .replace(/Ocultar Teoria/g, "Hide Theory")
      .replace(/ANÁLISE INDIVIDUALIZADA/g, "INDIVIDUALIZED ANALYSIS")
      .replace(/Ciclos primários/g, "Primary cycles")
      .replace(/Ciclos secundários/g, "Secondary cycles")
      .replace(/Potencial de Coexistência:/g, "Coexistence Potential:")
      .replace(/Diagrama do firmamento no nascimento/g, "Diagram of the firmament at birth")
      .replace(/A Balança Astrológica/g, "The Astrological Scale")
      .replace(/DNA Astral & Pesos de Personalidade/g, "Astral DNA & Personality Weights")
      .replace(/Comparar Mapas/g, "Compare Charts")
      .replace(/🔮 Mapa Principal Ativo/g, "🔮 Active Main Chart")
      .replace(/Nascimento:/g, "Birth:")
      .replace(/Não informado/g, "Not informed")
      .replace(/Dados da outra pessoa/g, "Other person details")
      .replace(/NOME DA PESSOA/g, "PERSON NAME")
      .replace(/Nome completo/g, "Full name")
      .replace(/DATA DE NASCIMENTO/g, "DATE OF BIRTH")
      .replace(/HORA DE NASCIMENTO/g, "TIME OF BIRTH")
      .replace(/CIDADE E PAÍS DE NASCIMENTO/g, "CITY AND COUNTRY OF BIRTH")
      .replace(/Cidade e país de nascimento/g, "City and country of birth")
      .replace(/Efetuar Cruzamento de Mapas/g, "Perform Chart Cross-Analysis")
      .replace(/Efetuando Alinhamento.../g, "Performing Alignment...")
      .replace(/Carregando.../g, "Loading...")
      .replace(/Sucesso!/g, "Success!")
      .replace(/Erro/g, "Error")
      .replace(/Salvar Alterações/g, "Save Changes")
      .replace(/Salvar/g, "Save")
      .replace(/Cancelar/g, "Cancel")
      .replace(/Confirmar/g, "Confirm")
      .replace(/Continuar/g, "Continue")
      .replace(/Editar/g, "Edit")
      .replace(/Excluir/g, "Delete")
      .replace(/Voltar/g, "Back")
      .replace(/Fechar/g, "Close")
      .replace(/Copiar/g, "Copy")
      .replace(/Copiado!/g, "Copied!")
      .replace(/Compartilhar/g, "Share")
      .replace(/Detalhes/g, "Details")
      .replace(/Visualizar/g, "View")
      .replace(/Histórico/g, "History")
      .replace(/Notificações/g, "Notifications")
      .replace(/Hoje:/g, "Today:")
      .replace(/Hoje/g, "Today")
      .replace(/Ontem/g, "Yesterday")
      .replace(/Amanhã/g, "Tomorrow")
      .replace(/Próximo Domingo/g, "Next Sunday")
      .replace(/às /g, "at ")
      .replace(/ em /g, " in ");
  } else if (lang === 'es') {
    // Spanish substitutions
    res = res
      .replace(/Configurações do Aplicativo/g, "Configuración de la Aplicación")
      .replace(/Configurações/g, "Configuración")
      .replace(/Módulo Astrologia Premium/g, "Módulo de Astrología Premium")
      .replace(/Meu Mapa Astral Completo/g, "Mi Carta Astral Completa")
      .replace(/Calculado sob o sistema/g, "Calculado bajo el sistema")
      .replace(/Mapa Interativo de Autoconhecimento/g, "Mapa Interactivo de Autoconocimiento")
      .replace(/Distribuição Energética/g, "Distribución Energética")
      .replace(/Posição dos Astros/g, "Posición de los Astros")
      .replace(/Casas Astrológicas/g, "Casas Astrológicas")
      .replace(/Aspectos Planetários/g, "Aspectos Planetarios")
      .replace(/Seções do Mapa/g, "Secciones de la Carta")
      .replace(/Recalcular Meu Mapa/g, "Recalcular Mi Carta")
      .replace(/Substituir Mapa Atual/g, "Reemplazar Carta Actual")
      .replace(/Radar Biológico & Tendências/g, "Radar Biológico y Tendencias")
      .replace(/Radar Diário/g, "Radar Diario")
      .replace(/Influências transitórias de hoje/g, "Influencias transitorias de hoy")
      .replace(/Frequência Regente/g, "Frecuencia Regente")
      .replace(/Nível de Disposição Física/g, "Nivel de Disposición Física")
      .replace(/Melhores Janelas Horas:/g, "Mejores Ventanas Horarias:")
      .replace(/Sincronismo Quântico Ativado/g, "Sincronismo Cuántico Activado")
      .replace(/Sintonização do Potencial de Vida/g, "Sintonización del Potencial de Vida")
      .replace(/Meu Biorritmo/g, "Mi Biorritmo")
      .replace(/Saiba Mais/g, "Saber Más")
      .replace(/Ocultar Teoria/g, "Ocultar Teoría")
      .replace(/ANÁLISE INDIVIDUALIZADA/g, "ANÁLISIS INDIVIDUALIZADO")
      .replace(/Ciclos primários/g, "Ciclos primarios")
      .replace(/Ciclos secundários/g, "Ciclos secundarios")
      .replace(/Potencial de Coexistência:/g, "Potencial de Coexistencia:")
      .replace(/Diagrama do firmamento no nascimento/g, "Diagrama del firmamento al nacer")
      .replace(/A Balança Astrológica/g, "La Balanza Astrológica")
      .replace(/DNA Astral & Pesos de Personalidade/g, "ADN Astral y Pesos de Personalidad")
      .replace(/Comparar Mapas/g, "Comparar Cartas")
      .replace(/🔮 Mapa Principal Ativo/g, "🔮 Carta Principal Activa")
      .replace(/Nascimento:/g, "Nacimiento:")
      .replace(/Não informado/g, "No informado")
      .replace(/Dados da outra pessoa/g, "Datos de la otra persona")
      .replace(/NOME DA PESSOA/g, "NOMBRE DE LA PERSONA")
      .replace(/Nome completo/g, "Nombre completo")
      .replace(/DATA DE NASCIMENTO/g, "FECHA DE NACIMIENTO")
      .replace(/HORA DE NASCIMENTO/g, "HORA DE NACIMIENTO")
      .replace(/CIDADE E PAÍS DE NASCIMENTO/g, "CIUDAD Y PAÍS DE NACIMIENTO")
      .replace(/Cidade e país de nascimento/g, "Ciudad y país de nacimiento")
      .replace(/Efetuar Cruzamento de Mapas/g, "Efectuar Cruzamiento de Cartas")
      .replace(/Efetuando Alinhamento.../g, "Efectuando Alineación...")
      .replace(/Carregando.../g, "Cargando...")
      .replace(/Sucesso!/g, "¡Éxito!")
      .replace(/Erro/g, "Error")
      .replace(/Salvar Alterações/g, "Guardar Cambios")
      .replace(/Salvar/g, "Guardar")
      .replace(/Cancelar/g, "Cancelar")
      .replace(/Confirmar/g, "Confirmar")
      .replace(/Continuar/g, "Continuar")
      .replace(/Editar/g, "Editar")
      .replace(/Excluir/g, "Eliminar")
      .replace(/Voltar/g, "Volver")
      .replace(/Fechar/g, "Cerrar")
      .replace(/Copiar/g, "Copiar")
      .replace(/Copiado!/g, "¡Copiado!")
      .replace(/Compartilhar/g, "Compartir")
      .replace(/Detalhes/g, "Detalles")
      .replace(/Visualizar/g, "Ver")
      .replace(/Histórico/g, "Historial")
      .replace(/Notificações/g, "Notificaciones")
      .replace(/Hoje:/g, "Hoy:")
      .replace(/Hoje/g, "Hoy")
      .replace(/Ontem/g, "Ayer")
      .replace(/Amanhã/g, "Mañana")
      .replace(/Próximo Domingo/g, "Próximo Domingo")
      .replace(/às /g, "a las ")
      .replace(/ em /g, " en ");
  } else if (lang === 'de') {
    // German substitutions
    res = res
      .replace(/Configurações do Aplicativo/g, "App-Einstellungen")
      .replace(/Configurações/g, "Einstellungen")
      .replace(/Módulo Astrologia Premium/g, "Premium Astrologiemodul")
      .replace(/Meu Mapa Astral Completo/g, "Mein Vollständiges Geburtshoroskop")
      .replace(/Calculado sob o sistema/g, "Berechnet nach dem System")
      .replace(/Mapa Interativo de Autoconhecimento/g, "Interaktives Selbsterkenntnis-Horoskop")
      .replace(/Distribuição Energética/g, "Energieverteilung")
      .replace(/Posição dos Astros/g, "Position der Gestirne")
      .replace(/Casas Astrológicas/g, "Astrologische Häuser")
      .replace(/Aspectos Planetários/g, "Planetarische Aspekte")
      .replace(/Seções do Mapa/g, "Horoskop-Abschnitte")
      .replace(/Recalcular Meu Mapa/g, "Mein Horoskop neu berechnen")
      .replace(/Substituir Mapa Atual/g, "Aktuelles Horoskop ersetzen")
      .replace(/Radar Biológico & Tendências/g, "Biologisches Radar & Trends")
      .replace(/Radar Diário/g, "Tagesradar")
      .replace(/Influências transitórias de hoje/g, "Heutige vorübergehende Einflüsse")
      .replace(/Frequência Regente/g, "Herrschende Frequenz")
      .replace(/Nível de Disposição Física/g, "Körperliches Energieniveau")
      .replace(/Melhores Janelas Horas:/g, "Beste Zeitfenster:")
      .replace(/Sincronismo Quântico Ativado/g, "Quantensynchronisation Aktiviert")
      .replace(/Sintonização do Potencial de Vida/g, "Einstimmung des Lebenspotenzials")
      .replace(/Meu Biorritmo/g, "Mein Biorhythmus")
      .replace(/Saiba Mais/g, "Mehr erfahren")
      .replace(/Ocultar Teoria/g, "Theorie ausblenden")
      .replace(/ANÁLISE INDIVIDUALIZADA/g, "INDIVIDUELLE ANALYSE")
      .replace(/Ciclos primários/g, "Primäre Zyklen")
      .replace(/Ciclos secundários/g, "Sekundäre Zyklen")
      .replace(/Potencial de Coexistência:/g, "Koexistenz-Potenzial:")
      .replace(/Diagrama do firmamento no nascimento/g, "Diagramm des Himmelsgewölbes bei der Geburt")
      .replace(/A Balança Astrológica/g, "Die Astrologische Waage")
      .replace(/DNA Astral & Pesos de Personalidade/g, "Astrale DNA & Persönlichkeitsgewichte")
      .replace(/Comparar Mapas/g, "Horoskope vergleichen")
      .replace(/🔮 Mapa Principal Ativo/g, "🔮 Aktives Haupthoroskop")
      .replace(/Nascimento:/g, "Geburt:")
      .replace(/Não informado/g, "Nicht angegeben")
      .replace(/Dados da outra pessoa/g, "Angaben der anderen Person")
      .replace(/NOME DA PESSOA/g, "NAME DER PERSON")
      .replace(/Nome completo/g, "Vollständiger Name")
      .replace(/DATA DE NASCIMENTO/g, "GEBURTSDATUM")
      .replace(/HORA DE NASCIMENTO/g, "GEBURTSZEIT")
      .replace(/CIDADE E PAÍS DE NASCIMENTO/g, "GEBURTSSTADT UND -LAND")
      .replace(/Cidade e país de nascimento/g, "Geburtsstadt und -land")
      .replace(/Efetuar Cruzamento de Mapas/g, "Horoskop-Abgleich durchführen")
      .replace(/Efetuando Alinhamento.../g, "Ausrichtung wird durchgeführt...")
      .replace(/Carregando.../g, "Wird geladen...")
      .replace(/Sucesso!/g, "Erfolg!")
      .replace(/Erro/g, "Fehler")
      .replace(/Salvar Alterações/g, "Änderungen speichern")
      .replace(/Salvar/g, "Speichern")
      .replace(/Cancelar/g, "Abbrechen")
      .replace(/Confirmar/g, "Bestätigen")
      .replace(/Continuar/g, "Fortfahren")
      .replace(/Editar/g, "Bearbeiten")
      .replace(/Excluir/g, "Löschen")
      .replace(/Voltar/g, "Zurück")
      .replace(/Fechar/g, "Schließen")
      .replace(/Copiar/g, "Kopieren")
      .replace(/Copiado!/g, "Kopiert!")
      .replace(/Compartilhar/g, "Teilen")
      .replace(/Detalhes/g, "Details")
      .replace(/Visualizar/g, "Ansehen")
      .replace(/Histórico/g, "Verlauf")
      .replace(/Notificações/g, "Benachrichtigungen")
      .replace(/Hoje:/g, "Heute:")
      .replace(/Hoje/g, "Heute")
      .replace(/Ontem/g, "Gestern")
      .replace(/Amanhã/g, "Morgen")
      .replace(/Próximo Domingo/g, "Nächster Sonntag")
      .replace(/às /g, "um ")
      .replace(/ em /g, " in ");
  } else if (lang === 'fr') {
    // French substitutions
    res = res
      .replace(/Configurações do Aplicativo/g, "Paramètres de l'Application")
      .replace(/Configurações/g, "Paramètres")
      .replace(/Módulo Astrologia Premium/g, "Module d'Astrologie Premium")
      .replace(/Meu Mapa Astral Completo/g, "Mon Thème Astral Complet")
      .replace(/Calculado sob o sistema/g, "Calculé selon le système")
      .replace(/Mapa Interativo de Autoconhecimento/g, "Carte Interactive de Connaissance de Soi")
      .replace(/Distribuição Energética/g, "Répartition Énergétique")
      .replace(/Posição dos Astros/g, "Position des Astres")
      .replace(/Casas Astrológicas/g, "Maisons Astrologiques")
      .replace(/Aspectos Planetários/g, "Aspectos Planétaires")
      .replace(/Seções do Mapa/g, "Sections du Thème")
      .replace(/Recalcular Meu Mapa/g, "Recalculer Mon Thème")
      .replace(/Substituir Mapa Atual/g, "Remplacer le Thème Actuel")
      .replace(/Radar Biológico & Tendências/g, "Radar Biologique & Tendances")
      .replace(/Radar Diário/g, "Radar Quotidien")
      .replace(/Influências transitórias de hoje/g, "Influences transitoires d'aujourd'hui")
      .replace(/Frequência Regente/g, "Fréquence Régente")
      .replace(/Nível de Disposição Física/g, "Niveau de Disposition Physique")
      .replace(/Melhores Janelas Horas:/g, "Meilleurs Créneaux Horaires :")
      .replace(/Sincronismo Quântico Ativado/g, "Synchronisme Quantique Activé")
      .replace(/Sintonização do Potencial de Vida/g, "Harmonisation du Potentiel de Vie")
      .replace(/Meu Biorritmo/g, "Mon Biorythme")
      .replace(/Saiba Mais/g, "En savoir plus")
      .replace(/Ocultar Teoria/g, "Masquer la Théorie")
      .replace(/ANÁLISE INDIVIDUALIZADA/g, "ANALYSE INDIVIDUALISÉE")
      .replace(/Ciclos primários/g, "Cycles primaires")
      .replace(/Ciclos secundários/g, "Cycles secondaires")
      .replace(/Potencial de Coexistência:/g, "Potentiel de Coexistence :")
      .replace(/Diagrama do firmamento no nascimento/g, "Diagramme du firmament à la naissance")
      .replace(/A Balança Astrológica/g, "La Balance Astrologique")
      .replace(/DNA Astral & Pesos de Personalidade/g, "ADN Astral & Poids de Personnalité")
      .replace(/Comparar Mapas/g, "Comparer les Thèmes")
      .replace(/🔮 Mapa Principal Ativo/g, "🔮 Thème Principal Actif")
      .replace(/Nascimento:/g, "Naissance :")
      .replace(/Não informado/g, "Non renseigné")
      .replace(/Dados da outra pessoa/g, "Informations sur l'autre personne")
      .replace(/NOME DA PESSOA/g, "NOM DE LA PERSONNE")
      .replace(/Nome completo/g, "Nom complet")
      .replace(/DATA DE NASCIMENTO/g, "DATE DE NAISSANCE")
      .replace(/HORA DE NASCIMENTO/g, "HEURE DE NAISSANCE")
      .replace(/CIDADE E PAÍS DE NASCIMENTO/g, "VILLE ET PAYS DE NAISSANCE")
      .replace(/Cidade e país de nascimento/g, "Ville et pays de naissance")
      .replace(/Efetuar Cruzamento de Mapas/g, "Effectuer le Croisement des Thèmes")
      .replace(/Efetuando Alinhamento.../g, "Alignement en cours...")
      .replace(/Carregando.../g, "Chargement...")
      .replace(/Sucesso!/g, "Succès !")
      .replace(/Erro/g, "Erreur")
      .replace(/Salvar Alterações/g, "Enregistrer les modifications")
      .replace(/Salvar/g, "Enregistrer")
      .replace(/Cancelar/g, "Annuler")
      .replace(/Confirmar/g, "Confirmer")
      .replace(/Continuar/g, "Continuer")
      .replace(/Editar/g, "Modifier")
      .replace(/Excluir/g, "Supprimer")
      .replace(/Voltar/g, "Retour")
      .replace(/Fechar/g, "Fermer")
      .replace(/Copiar/g, "Copier")
      .replace(/Copiado!/g, "Copié !")
      .replace(/Compartilhar/g, "Partager")
      .replace(/Detalhes/g, "Détails")
      .replace(/Visualizar/g, "Afficher")
      .replace(/Histórico/g, "Historique")
      .replace(/Notificações/g, "Notifications")
      .replace(/Hoje:/g, "Aujourd'hui :")
      .replace(/Hoje/g, "Aujourd'hui")
      .replace(/Ontem/g, "Hier")
      .replace(/Amanhã/g, "Demain")
      .replace(/Próximo Domingo/g, "Dimanche Prochain")
      .replace(/às /g, "à ")
      .replace(/ em /g, " en ");
  }

  return res;
}

console.log('Translator function ready.');
