import * as fs from 'fs';
import * as path from 'path';

import { autoAuditPatch } from '../lib/autoAuditPatch';
import { mergedTranslations } from '../i18n';

// Translation map for the remaining 328 keys
const translations328: Record<string, { en: string; es: string; de: string; fr: string }> = {
  "premium": { en: "Premium", es: "Premium", de: "Premium", fr: "Premium" },
  "tarot": { en: "Tarot", es: "Tarot", de: "Tarot", fr: "Tarot" },
  "lang_pt_name": { en: "Portuguese (BR)", es: "Portugués (BR)", de: "Portugiesisch (BR)", fr: "Portugais (BR)" },
  "lang_en_name": { en: "English (US)", es: "Inglés (EE. UU.)", de: "Englisch (US)", fr: "Anglais (US)" },
  "lang_es_name": { en: "Spanish (ES)", es: "Español (ES)", de: "Spanisch (ES)", fr: "Espagnol (ES)" },
  "lang_de_name": { en: "German (DE)", es: "Alemán (DE)", de: "Deutsch (DE)", fr: "Allemand (DE)" },
  "lang_fr_name": { en: "French (FR)", es: "Francés (FR)", de: "Französisch (FR)", fr: "Français (FR)" },
  "admin.free_tier": { en: "Free Tier", es: "Nivel Gratuito", de: "Kostenlose Stufe", fr: "Niveau Gratuit" },
  "admin.basic_plan": { en: "Basic Plan", es: "Plan Básico", de: "Basis-Plan", fr: "Plan De Base" },
  "admin.astro_premium": { en: "Astro Premium", es: "Astro Premium", de: "Astro Premium", fr: "Astro Premium" },
  "admin.celestial_vip": { en: "Celestial VIP", es: "VIP Celestial", de: "Himmlisches VIP", fr: "VIP Céleste" },
  "sub_status": { en: "Subscription Status", es: "Estado de Suscripción", de: "Abonnementstatus", fr: "Statut d'Abonnement" },
  "year": { en: "Year", es: "Año", de: "Jahr", fr: "Année" },
  "month": { en: "Month", es: "Mes", de: "Monat", fr: "Mois" },
  "degree": { en: "Degree", es: "Grado", de: "Grad", fr: "Degré" },
  "Abrir Dica Lunar Rápida": { en: "Open Quick Lunar Tip", es: "Abrir Consejo Lunar Rápido", de: "Schnellen Mondtipp öffnen", fr: "Ouvrir le Conseil Lunaire Rapide" },
  "Sussurro Lunar Diário": { en: "Daily Lunar Whisper", es: "Susurro Lunar Diario", de: "Tägliches Mondflüstern", fr: "Chuchotement Lunaire Quotidien" },
  "Minimizar dica": { en: "Minimize tip", es: "Minimizar consejo", de: "Tipp minimieren", fr: "Minimiser le conseil" },
  "Foco Conectado": { en: "Focus Connected", es: "Enfoque Conectado", de: "Fokus Verbunden", fr: "Focus Connecté" },
  "+150 Pontos Ativados": { en: "+150 Points Activated", es: "+150 Puntos Activados", de: "+150 Punkte Aktiviert", fr: "+150 Points Activés" },
  "Venerar Lua (+150 pts)": { en: "Honor Moon (+150 pts)", es: "Venerar Luna (+150 pts)", de: "Mond ehren (+150 Pkt)", fr: "Vénérer la Lune (+150 pts)" },
  "Monitor em Tempo Real": { en: "Real-Time Monitor", es: "Monitor en Tiempo Real", de: "Echtzeit-Monitor", fr: "Moniteur en Temps Réel" },
  "Seus Trânsitos Horários e Energias do Dia": { en: "Your Hourly Transits and Daily Energies", es: "Tus Tránsitos Horarios y Energías del Día", de: "Ihre stündlichen Transite und Tagesenergien", fr: "Vos Transits Horaires et Énergies du Jour" },
  "Análise de como os planetas flutuam sobre sua composição natal de nascimento.": { en: "Analysis of how planets transit over your natal birth composition.", es: "Análisis de cómo los planetas transitan sobre tu composición natal de nacimiento.", de: "Analyse, wie Planeten über Ihre Geburtskonstellation wandern.", fr: "Analyse de la façon dont les planètes transitent sur votre composition natale." },
  "Sincronizado: Hoje": { en: "Synchronized: Today", es: "Sincronizado: Hoy", de: "Synchronisiert: Heute", fr: "Synchronisé : Aujourd'hui" },
  "Planetas Transitando no Céu": { en: "Planets Transiting in the Sky", es: "Planetas Transitando en el Cielo", de: "Am Himmel wandernde Planeten", fr: "Planètes en Transit dans le Ciel" },
  "Pontuações Celestes Planas": { en: "Flat Celestial Scores", es: "Puntuaciones Celestes Planas", de: "Flache Himmelswerte", fr: "Scores Célestes Plats" },
  "Criatividade e Alinhamento": { en: "Creativity and Alignment", es: "Creatividad y Alineación", de: "Kreativität und Ausrichtung", fr: "Créativité et Alignement" },
  "Diálogo e Escrita": { en: "Dialogue and Writing", es: "Diálogo y Escritura", de: "Dialog und Schreiben", fr: "Dialogue et Écriture" },
  "Vontade Física e Esporte": { en: "Physical Drive and Sport", es: "Impulso Físico y Deporte", de: "Körperlicher Antrieb und Sport", fr: "Élan Physique et Sport" },
  "Dica do Oráculo:": { en: "Oracle Tip:", es: "Consejo del Oráculo:", de: "Orakel-Tipp:", fr: "Conseil de l'Oracle :" },
  "Hoje o fluxo solar favorece a revisão estrutural. Ótimo período para finalizar escritos e praticar interiorizações sem pressões externas deletérias.": { en: "Today solar flow favors structural review. Great time to finalize writings and engage in inner reflection without harmful external pressure.", es: "Hoy el flujo solar favorece la revisión estructural. Gran momento para finalizar escritos y practicar la introspección sin presiones externas perjudiciales.", de: "Heute begünstigt der Sonnenfluss die strukturelle Überprüfung. Tolle Zeit, um Texte fertigzustellen und innere Einkehr ohne schädlichen äußeren Druck zu praktizieren.", fr: "Aujourd'hui, le flux solaire favorise la révision structurelle. Moment idéal pour finaliser des écrits et pratiquer l'introspection sans pressions externes nocives." },
  "Aries": { en: "Aries", es: "Aries", de: "Widder", fr: "Bélier" },
  "Taurus": { en: "Taurus", es: "Tauro", de: "Stier", fr: "Taureau" },
  "Gemini": { en: "Gemini", es: "Géminis", de: "Zwillinge", fr: "Gémeaux" },
  "Cancer": { en: "Cancer", es: "Cáncer", de: "Krebs", fr: "Cancer" },
  "Leo": { en: "Leo", es: "Leo", de: "Löwe", fr: "Lion" },
  "Virgo": { en: "Virgo", es: "Virgo", de: "Jungfrau", fr: "Vierge" },
  "Libra": { en: "Libra", es: "Libra", de: "Waage", fr: "Balance" },
  "Scorpio": { en: "Scorpio", es: "Escorpio", de: "Skorpion", fr: "Scorpion" },
  "Sagittarius": { en: "Sagittarius", es: "Sagitario", de: "Schütze", fr: "Sagittaire" },
  "Capricorn": { en: "Capricorn", es: "Capricornio", de: "Steinbock", fr: "Capricorne" },
  "Aquarius": { en: "Aquarius", es: "Acuario", de: "Wassermann", fr: "Verseau" },
  "Pisces": { en: "Pisces", es: "Piscis", de: "Fische", fr: "Poissons" },

  // Auth, Firestore & Cloud Sync Toasts
  "Este e-mail já possui uma conta cadastrada. Redirecionando para a tela de login...": { en: "This email already has a registered account. Redirecting to login...", es: "Este correo electrónico ya tiene una cuenta registrada. Redirigiendo al inicio de sesión...", de: "Für diese E-Mail-Adresse existiert bereits ein Konto. Weiterleitung zur Anmeldung...", fr: "Cet e-mail possède déjà un compte enregistré. Redirection vers la page de connexion..." },
  "Erro no cadastro. Verifique a senha (mínimo 6 caracteres).": { en: "Registration error. Check password (minimum 6 characters).", es: "Error de registro. Verifique la contraseña (mínimo 6 caracteres).", de: "Registrierungsfehler. Überprüfen Sie das Passwort (mindestens 6 Zeichen).", fr: "Erreur d'inscription. Vérifiez le mot de passe (minimum 6 caractères)." },
  "Conta criada com sucesso! Enviamos um link de confirmação para o seu e-mail.": { en: "Account created successfully! We sent a confirmation link to your email.", es: "¡Cuenta creada con éxito! Enviamos un enlace de confirmación a tu correo electrónico.", de: "Konto erfolgreich erstellt! Wir haben einen Bestätigungslink an Ihre E-Mail gesendet.", fr: "Compte créé avec succès ! Nous avons envoyé un lien de confirmation à votre e-mail." },
  "Erro de Login": { en: "Login Error", es: "Error de Inicio de Sesión", de: "Anmeldefehler", fr: "Erreur de Connexion" },
  "Por favor, digite seu E-mail e Senha de acesso.": { en: "Please enter your Email and Password.", es: "Por favor, introduce tu Correo electrónico y Contraseña.", de: "Bitte geben Sie Ihre E-Mail und Ihr Passwort ein.", fr: "Veuillez saisir votre E-mail et votre Mot de passe." },
  "E-mail ou senha incorretos. Tente novamente ou cadastre-se.": { en: "Incorrect email or password. Try again or sign up.", es: "Correo o contraseña incorrectos. Inténtelo de nuevo o regístrese.", de: "Falsche E-Mail oder Passwort. Versuchen Sie es erneut oder registrieren Sie sich.", fr: "E-mail ou mot de passe incorrect. Réessayez ou inscrivez-vous." },
  "Mapa Sincronizado": { en: "Chart Synchronized", es: "Carta Sincronizada", de: "Horoskop Synchronisiert", fr: "Thème Synchronisé" },
  "Seu mapa astral local foi arquivado com sucesso no seu perfil na nuvem!": { en: "Your local birth chart was successfully archived to your cloud profile!", es: "¡Tu carta astral local se ha archivado con éxito en tu perfil en la nube!", de: "Ihr lokales Geburtshoroskop wurde erfolgreich in Ihrem Cloud-Profil archiviert!", fr: "Votre thème astral local a été archivé avec succès dans votre profil cloud !" },
  "Autenticação Necessária": { en: "Authentication Required", es: "Autenticación Requerida", de: "Authentifizierung Erforderlich", fr: "Authentification Requise" },
  "Crie uma conta ou faça login para salvar seu mapa com segurança na Nuvem Órbita!": { en: "Create an account or log in to save your chart securely to the Órbita Cloud!", es: "¡Crea una cuenta o inicia sesión para guardar tu carta de forma segura en la Nube Órbita!", de: "Erstellen Sie ein Konto oder melden Sie sich an, um Ihr Horoskop sicher in der Órbita-Cloud zu speichern!", fr: "Créez un compte ou connectez-vous pour enregistrer votre thème en toute sécurité dans le Cloud Órbita !" },
  "Sem Dados do Mapa": { en: "No Chart Data", es: "Sin Datos de la Carta", de: "Keine Horoskopdaten", fr: "Aucune Donnée de Thème" },
  "Por favor, insira seus dados de nascimento para gerar um mapa antes de salvar.": { en: "Please enter your birth details to generate a chart before saving.", es: "Por favor, introduce tus datos de nacimiento para generar una carta antes de guardar.", de: "Bitte geben Sie Ihre Geburtsdaten ein, um vor dem Speichern ein Horoskop zu erstellen.", fr: "Veuillez saisir vos données de naissance pour générer un thème avant d'enregistrer." },
  "Sincronização Completa": { en: "Synchronization Complete", es: "Sincronización Completa", de: "Synchronisation Abgeschlossen", fr: "Synchronisation Complète" },
  "Seu mapa natal e numerologia foram salvos com sucesso na nuvem do Firestore!": { en: "Your birth chart and numerology have been successfully saved to the Firestore cloud!", es: "¡Tu carta natal y numerología se han guardado con éxito en la nube de Firestore!", de: "Ihr Geburtshoroskop und Ihre Numerologie wurden erfolgreich in der Firestore-Cloud gespeichert!", fr: "Votre thème natal et votre numérologie ont été enregistrés avec succès dans le cloud Firestore !" },
  "Erro Firestore:": { en: "Firestore Error:", es: "Error de Firestore:", de: "Firestore-Fehler:", fr: "Erreur Firestore :" },
  "Cache Limpo": { en: "Cache Cleared", es: "Caché Limpiada", de: "Cache Geleert", fr: "Cache Effacé" },
  "Seu cache de performance foi limpo e otimizado com segurança.": { en: "Your performance cache has been safely cleared and optimized.", es: "Tu caché de rendimiento se ha limpiado y optimizado de forma segura.", de: "Ihr Leistungs-Cache wurde sicher geleert und optimiert.", fr: "Votre cache de performance a été vidé et optimisé en toute sécurité." },
  "Erro de Limpeza": { en: "Cleanup Error", es: "Error de Limpieza", de: "Bereinigungsfehler", fr: "Erreur de Nettoyage" },
  "Falha ao limpar o cache temporário.": { en: "Failed to clear temporary cache.", es: "Error al limpiar la caché temporal.", de: "Fehler beim Leeren des temporären Caches.", fr: "Échec du nettoyage du cache temporaire." },
  "E-mail confirmado com sucesso! Bem-vindo ao Portal Órbita.": { en: "Email confirmed successfully! Welcome to Portal Órbita.", es: "¡Correo electrónico confirmado con éxito! Bienvenido al Portal Órbita.", de: "E-Mail erfolgreich bestätigt! Willkommen beim Portal Órbita.", fr: "E-mail confirmé avec succès ! Bienvenue sur le Portail Órbita." },
  "Ainda não verificado": { en: "Not yet verified", es: "Aún no verificado", de: "Noch nicht verifiziert", fr: "Pas encore vérifié" },
  "Não detectamos seu clique no link de e-mail ainda. Verifique sua caixa de entrada e spam, e tente novamente.": { en: "We haven't detected your click on the email link yet. Check your inbox and spam folder, and try again.", es: "Aún no hemos detectado tu clic en el enlace del correo. Revisa tu bandeja de entrada y spam, e inténtalo de nuevo.", de: "Wir haben Ihren Klick auf den E-Mail-Link noch nicht erkannt. Überprüfen Sie Ihren Posteingang und Spam-Ordner und versuchen Sie es erneut.", fr: "Nous n'avons pas encore détecté votre clic sur le lien e-mail. Vérifiez votre boîte de réception et vos spams, puis réessayez." },
  "Erro de Sincronização": { en: "Synchronization Error", es: "Error de Sincronización", de: "Synchronisationsfehler", fr: "Erreur de Synchronisation" },
  "Tente novamente mais tarde.": { en: "Try again later.", es: "Inténtalo de nuevo más tarde.", de: "Versuchen Sie es später erneut.", fr: "Réessayez plus tard." },
  "Um novo link oficial de ativação foi enviado para seu e-mail.": { en: "A new official activation link has been sent to your email.", es: "Se ha enviado un nuevo enlace oficial de activación a tu correo electrónico.", de: "Ein neuer offizieller Aktivierungslink wurde an Ihre E-Mail gesendet.", fr: "Un nouveau lien officiel d'activation a été envoyé à votre e-mail." },
  "Não foi possível enviar.": { en: "Could not send.", es: "No se pudo enviar.", de: "Konnte nicht gesendet werden.", fr: "Impossible d'envoyer." },
  "E-mail confirmado via bypass de teste. Bem-vindo ao Portal Órbita.": { en: "Email confirmed via test bypass. Welcome to Portal Órbita.", es: "Correo electrónico confirmado mediante bypass de prueba. Bienvenido al Portal Órbita.", de: "E-Mail über Test-Bypass bestätigt. Willkommen beim Portal Órbita.", fr: "E-mail confirmé via le contournement de test. Bienvenue sur le Portail Órbita." },
  "Ignorar Confirmação (Apenas para Apresentações/Mock)": { en: "Skip Confirmation (Only for Presentations/Mock)", es: "Ignorar Confirmación (Solo para Presentaciones/Mock)", de: "Bestätigung überspringen (Nur für Präsentationen/Mock)", fr: "Ignorer la Confirmation (Uniquement pour Présentations/Mock)" },
  "Sessão Encerrada": { en: "Session Ended", es: "Sesión Finalizada", de: "Sitzung Beendet", fr: "Session Terminée" },
  "Você retornou ao portal.": { en: "You have returned to the portal.", es: "Has regresado al portal.", de: "Sie sind zum Portal zurückgekehrt.", fr: "Vous êtes retourné au portail." },
  "Voltar ao Início / Trocar de Conta": { en: "Back to Home / Switch Account", es: "Volver al Inicio / Cambiar de Cuenta", de: "Zurück zur Startseite / Konto wechseln", fr: "Retour à l'Accueil / Changer de Compte" },
  "Você reivindicou com sucesso seu bônus diário do Sussurro Lunar": { en: "You have successfully claimed your daily Lunar Whisper bonus", es: "Has reclamado con éxito tu bono diario del Susurro Lunar", de: "Sie haben Ihren täglichen Mondflüstern-Bonus erfolgreich eingelöst", fr: "Vous avez réclamé avec succès votre bonus quotidien du Chuchotement Lunaire" },
  "pontos": { en: "points", es: "puntos", de: "Punkte", fr: "points" },
  "Registre-se": { en: "Register", es: "Regístrate", de: "Registrieren", fr: "S'inscrire" },
  "Crie sua conta para sincronizar e salvar este mapa para sempre na nuvem!": { en: "Create your account to sync and save this chart forever in the cloud!", es: "¡Crea tu cuenta para sincronizar y guardar esta carta para siempre en la nube!", de: "Erstellen Sie Ihr Konto, um dieses Horoskop für immer in der Cloud zu synchronisieren und zu speichern!", fr: "Créez votre compte pour synchroniser et enregistrer ce thème pour toujours dans le cloud !" },
  "Portal Sair": { en: "Exit Portal", es: "Salir del Portal", de: "Portal verlassen", fr: "Quitter le Portail" },
  "Sessão encerrada com sucesso.": { en: "Session ended successfully.", es: "Sesión cerrada con éxito.", de: "Sitzung erfolgreich beendet.", fr: "Session terminée avec succès." },
  "Avatar Celestial": { en: "Celestial Avatar", es: "Avatar Celestial", de: "Himmlischer Avatar", fr: "Avatar Céleste" },
  "Sua essência foi sintonizada com o arquétipo do": { en: "Your essence was tuned with the archetype of", es: "Tu esencia fue sintonizada con el arquetipo de", de: "Ihre Essenz wurde auf den Archetyp abgestimmt von", fr: "Votre essence a été accordée avec l'archétype de" },
  "Arquétipo": { en: "Archetype", es: "Arquetipo", de: "Archetyp", fr: "Archétype" },

  // UI Keys & Settings
  "ui.profile.defaultSeeker": { en: "Cosmic Seeker", es: "Buscador Cósmico", de: "Kosmischer Sucher", fr: "Chercheur Cosmique" },
  "ui.accessibility.toggleHighContrast": { en: "Toggle High Contrast", es: "Alternar Alto Contraste", de: "Hohen Kontrast umschalten", fr: "Basculer le Contraste Élevé" },
  "edit_coords": { en: "Edit Coordinates", es: "Editar Coordenadas", de: "Koordinaten bearbeiten", fr: "Modifier les Coordonnées" },
  "preferred_lang": { en: "Preferred Language", es: "Idioma Preferido", de: "Bevorzugte Sprache", fr: "Langue Préférée" },
  "high_contrast": { en: "High Contrast", es: "Alto Contraste", de: "Hoher Kontrast", fr: "Contraste Élevé" },
  "menu_map": { en: "Astral Chart", es: "Carta Astral", de: "Geburtshoroskop", fr: "Thème Astral" },
  "menu_planets": { en: "Planets & Houses", es: "Planetas y Casas", de: "Planeten & Häuser", fr: "Planètes et Maisons" },
  "sms_reminders": { en: "SMS Reminders", es: "Recordatorios por SMS", de: "SMS-Erinnerungen", fr: "Rappels par SMS" },
  "delete_confirm_cancel": { en: "Cancel Account Deletion", es: "Cancelar Eliminación de Cuenta", de: "Kontolöschung abbrechen", fr: "Annuler la Suppression de Compte" },
  "Idealista": { en: "Idealist", es: "Idealista", de: "Idealist", fr: "Idéaliste" },
  "Socialmente consciente": { en: "Socially conscious", es: "Socialmente consciente", de: "Sozial bewusst", fr: "Socialement conscient" },
  "Inventivo": { en: "Inventive", es: "Inventivo", de: "Erfinderisch", fr: "Inventif" },
  "Curioso": { en: "Curious", es: "Curioso", de: "Neugierig", fr: "Curieux" },
  "Disperso": { en: "Scattered", es: "Disperso", de: "Zerstreut", fr: "Dispersé" },
  "Inquieto": { en: "Restless", es: "Inquieto", de: "Rastlos", fr: "Inquiet" },
  "Signos": { en: "Signs", es: "Signos", de: "Sternzeichen", fr: "Signes" },
  "Casas": { en: "Houses", es: "Casas", de: "Häuser", fr: "Maisons" },
  "Planetas": { en: "Planets", es: "Planetas", de: "Planeten", fr: "Planètes" },
  "Amor": { en: "Love", es: "Amor", de: "Liebe", fr: "Amour" },
  "Amuleto:": { en: "Amulet:", es: "Amuleto:", de: "Amulett:", fr: "Amulette :" },
  "Astro Sintonizador Local": { en: "Local Astro Tuner", es: "Sintonizador Astro Local", de: "Lokaler Astro-Tuner", fr: "Syntoniseur Astro Local" },
  "Avatar Sintonizado": { en: "Avatar Tuned", es: "Avatar Sintonizado", de: "Avatar Eingestimmt", fr: "Avatar Accordé" },
  "Casa": { en: "House", es: "Casa", de: "Haus", fr: "Maison" },
  "Casas Astrológicas": { en: "Astrological Houses", es: "Casas Astrológicas", de: "Astrologische Häuser", fr: "Maisons Astrologiques" },
  "Emocional": { en: "Emotional", es: "Emocional", de: "Emotional", fr: "Émotionnel" },
  "Instalado": { en: "Installed", es: "Instalado", de: "Installiert", fr: "Installé" },
  "Planeta": { en: "Planet", es: "Planeta", de: "Planet", fr: "Planète" },
  "Sintonizado": { en: "Tuned", es: "Sintonizado", de: "Eingestimmt", fr: "Accordé" },
  "Sintonizado com": { en: "Tuned with", es: "Sintonizado con", de: "Eingestimmt auf", fr: "Accordé avec" },
  "★ Sintonizado com seu Mapa Real": { en: "★ Tuned with your Real Chart", es: "★ Sintonizado con tu Carta Real", de: "★ Auf Ihr Reales Horoskop abgestimmt", fr: "★ Accordé avec votre Thème Réel" },
  "✦ Alto Potencial": { en: "✦ High Potential", es: "✦ Alto Potencial", de: "✦ Hohes Potenzial", fr: "✦ Haut Potentiel" },
  "Intuitivo": { en: "Intuitive", es: "Intuitivo", de: "Intuitiv", fr: "Intuitif" },
  "Físico": { en: "Physical", es: "Físico", de: "Physisch", fr: "Physique" },
  "Intelectual": { en: "Intellectual", es: "Intelectual", de: "Intellektuell", fr: "Intellectuel" },
  "Perceptivo": { en: "Perceptive", es: "Perceptivo", de: "Wahrnehmend", fr: "Perceptif" },
  "Estético": { en: "Aesthetic", es: "Estético", de: "Ästhetisch", fr: "Esthétique" },
  "Neptun": { en: "Neptune", es: "Neptuno", de: "Neptun", fr: "Neptune" },
  "Merkur": { en: "Mercury", es: "Mercurio", de: "Merkur", fr: "Mercure" },
  "Mond": { en: "Moon", es: "Luna", de: "Mond", fr: "Lune" },
  "Konjunktion": { en: "Conjunction", es: "Conjunción", de: "Konjunktion", fr: "Conjonction" },
  "Quadrat": { en: "Square", es: "Cuadratura", de: "Quadrat", fr: "Carré" },
  "(E-mail)": { en: "(Email)", es: "(Correo)", de: "(E-Mail)", fr: "(E-mail)" },
  "Mercure": { en: "Mercury", es: "Mercurio", de: "Merkur", fr: "Mercure" },
  "Vénus": { en: "Venus", es: "Venus", de: "Venus", fr: "Vénus" },
  "Lune": { en: "Moon", es: "Luna", de: "Mond", fr: "Lune" },
  "Conjonction": { en: "Conjunction", es: "Conjunción", de: "Konjunktion", fr: "Conjonction" },
  "Carré": { en: "Square", es: "Cuadratura", de: "Quadrat", fr: "Carré" },
  "São Paulo, SP": { en: "São Paulo, SP", es: "São Paulo, SP", de: "São Paulo, SP", fr: "São Paulo, SP" },
  "Instagram (@usuario)": { en: "Instagram (@username)", es: "Instagram (@usuario)", de: "Instagram (@benutzer)", fr: "Instagram (@utilisateur)" },
  "numberSymbols": { en: "🔢 Number Symbols Revealed", es: "🔢 Símbolos de Números Revelados", de: "🔢 Offenbarte Zahlensymbole", fr: "🔢 Symboles Numériques Révélés" }
};

// Apply all entries to autoAuditPatch
for (const lang of ['en', 'es', 'de', 'fr'] as const) {
  for (const [key, tr] of Object.entries(translations328)) {
    autoAuditPatch[lang][key] = tr[lang];
  }
}

// Write the updated file
const fileContent = `// Auto-generated 100% complete translation patch
export const autoAuditPatch: Record<'en' | 'es' | 'de' | 'fr', Record<string, string>> = ${JSON.stringify(autoAuditPatch, null, 2)};
`;

fs.writeFileSync(path.resolve('src/lib/autoAuditPatch.ts'), fileContent, 'utf8');
console.log(`Updated autoAuditPatch.ts with ${Object.keys(translations328).length} exact translations.`);
