import * as fs from 'fs';
import * as path from 'path';

// Master translation dictionaries and phrase replacement engine
const inputKeys: { key: string; pt: string }[] = JSON.parse(fs.readFileSync('untranslated-keys.json', 'utf8'));

// Exact phrase maps for the 1177 keys
const exactMap: Record<string, { en: string; es: string; de: string; fr: string }> = {
  "premium": { en: "Premium", es: "Premium", de: "Premium", fr: "Premium" },
  "profile": { en: "Profile", es: "Perfil", de: "Profil", fr: "Profil" },
  "email": { en: "Email", es: "Correo electrónico", de: "E-Mail", fr: "E-mail" },
  "lang_pt_name": { en: "Portuguese (BR)", es: "Portugués (BR)", de: "Portugiesisch (BR)", fr: "Portugais (BR)" },
  "lang_en_name": { en: "English (US)", es: "Inglés (EE. UU.)", de: "Englisch (US)", fr: "Anglais (US)" },
  "lang_es_name": { en: "Spanish (ES)", es: "Español (ES)", de: "Spanisch (ES)", fr: "Espagnol (ES)" },
  "lang_de_name": { en: "German (DE)", es: "Alemán (DE)", de: "Deutsch (DE)", fr: "Allemand (DE)" },
  "lang_fr_name": { en: "French (FR)", es: "Francés (FR)", de: "Französisch (FR)", fr: "Français (FR)" },
  "cancel": { en: "Cancel", es: "Cancelar", de: "Abbrechen", fr: "Annuler" },
  "appName": { en: "PORTAL ÓRBITA", es: "PORTAL ÓRBITA", de: "PORTAL ÓRBITA", fr: "PORTAL ÓRBITA" },
  "btnCancel": { en: "Cancel", es: "Cancelar", de: "Abbrechen", fr: "Annuler" },
  "admin.free_tier": { en: "Free Tier", es: "Nivel Gratuito", de: "Kostenlose Stufe", fr: "Niveau Gratuit" },
  "admin.basic_plan": { en: "Basic Plan", es: "Plan Básico", de: "Basis-Plan", fr: "Plan De Base" },
  "admin.astro_premium": { en: "Astro Premium", es: "Astro Premium", de: "Astro Premium", fr: "Astro Premium" },
  "admin.celestial_vip": { en: "Celestial VIP", es: "VIP Celestial", de: "Himmlisches VIP", fr: "VIP Céleste" },
  "dashboard.ruling_planet": { en: "Ruling Planet", es: "Planeta Regente", de: "Herrschender Planet", fr: "Planète Régente" },
  "dashboard.element": { en: "Element", es: "Elemento", de: "Element", fr: "Élément" },
  "Azul Cobalto Real": { en: "Royal Cobalt Blue", es: "Azul Cobalto Real", de: "Königs-Kobaltblau", fr: "Bleu Cobalt Royal" },
  "Violeta Estelar": { en: "Stellar Violet", es: "Violeta Estelar", de: "Stellare Violett", fr: "Violet Stellaire" },
  "Editar": { en: "Edit", es: "Editar", de: "Bearbeiten", fr: "Modifier" },
  "Excluir": { en: "Delete", es: "Eliminar", de: "Löschen", fr: "Supprimer" },
  "Salvar": { en: "Save", es: "Guardar", de: "Speichern", fr: "Enregistrer" },
  "Voltar": { en: "Back", es: "Volver", de: "Zurück", fr: "Retour" },
  "Fechar": { en: "Close", es: "Cerrar", de: "Schließen", fr: "Fermer" },
  "Copiar": { en: "Copy", es: "Copiar", de: "Kopieren", fr: "Copier" },
  "Copiado!": { en: "Copied!", es: "¡Copiado!", de: "Kopiert!", fr: "Copié !" },
  "Compartilhar": { en: "Share", es: "Compartir", de: "Teilen", fr: "Partager" },
  "Detalhes": { en: "Details", es: "Detalles", de: "Details", fr: "Détails" },
  "Visualizar": { en: "View", es: "Ver", de: "Ansehen", fr: "Afficher" },
  "Configurações": { en: "Settings", es: "Configuración", de: "Einstellungen", fr: "Paramètres" },
  "Início": { en: "Home", es: "Inicio", de: "Startseite", fr: "Accueil" },
  "Ajuda": { en: "Help", es: "Ayuda", de: "Hilfe", fr: "Aide" },
  "Sair": { en: "Log out", es: "Cerrar sesión", de: "Abmelden", fr: "Déconnexion" },
  "Entrar": { en: "Sign in", es: "Iniciar sesión", de: "Anmelden", fr: "Connexion" },
  "Cadastrar": { en: "Sign up", es: "Registrarse", de: "Registrieren", fr: "S'inscrire" },
  "Notificações": { en: "Notifications", es: "Notificaciones", de: "Benachrichtigungen", fr: "Notifications" },
  "Histórico": { en: "History", es: "Historial", de: "Verlauf", fr: "Historique" },
  "Carregando...": { en: "Loading...", es: "Cargando...", de: "Laden...", fr: "Chargement..." },
  "Sucesso!": { en: "Success!", es: "¡Éxito!", de: "Erfolg!", fr: "Succès !" },
  "Erro": { en: "Error", es: "Error", de: "Fehler", fr: "Erreur" },
  "Confirmar": { en: "Confirm", es: "Confirmar", de: "Bestätigen", fr: "Confirmer" },
  "Continuar": { en: "Continue", es: "Continuar", de: "Fortfahren", fr: "Continuer" },
  "Salvar Alterações": { en: "Save Changes", es: "Guardar cambios", de: "Änderungen speichern", fr: "Enregistrer les modifications" },
  "Dourado Solar": { en: "Solar Gold", es: "Dorado Solar", de: "Sonnengold", fr: "Or Solaire" },
  "Esmeralda Mística": { en: "Mystic Emerald", es: "Esmeralda Mística", de: "Mystisches Smaragd", fr: "Émeraude Mystique" },
  "Rubi Cósmico": { en: "Cosmic Ruby", es: "Rubí Cósmico", de: "Kosmischer Rubin", fr: "Rubis Cosmique" },
  "Qualidade": { en: "Quality", es: "Cualidad", de: "Qualität", fr: "Qualité" },
  "Polaridade": { en: "Polarity", es: "Polaridad", de: "Polarität", fr: "Polarité" },
  "Signo Solar": { en: "Sun Sign", es: "Signo Solar", de: "Sonnenzeichen", fr: "Signe Solaire" },
  "Signo Lunar": { en: "Moon Sign", es: "Signo Lunar", de: "Mondzeichen", fr: "Signe Lunaire" },
  "Ascendente": { en: "Ascendant", es: "Ascendente", de: "Aszendent", fr: "Ascendant" },
  "Meio do Céu": { en: "Midheaven", es: "Medio Cielo", de: "Medium Coeli", fr: "Milieu du Ciel" },
  "Fundo do Céu": { en: "Imum Coeli", es: "Fondo del Cielo", de: "Imum Coeli", fr: "Fond du Ciel" },
  "Descendente": { en: "Descendant", es: "Descendente", de: "Deszendent", fr: "Descendant" },
  "Nodo Norte": { en: "North Node", es: "Nodo Norte", de: "Nordknoten", fr: "Nœud Nord" },
  "Nodo Sul": { en: "South Node", es: "Nodo Sur", de: "Südknoten", fr: "Nœud Sud" },
  "Quíron": { en: "Chiron", es: "Quirón", de: "Chiron", fr: "Chiron" },
  "Lilith": { en: "Lilith", es: "Lilith", de: "Lilith", fr: "Lilith" },
  "Roda da Fortuna": { en: "Wheel of Fortune", es: "Rueda de la Fortuna", de: "Glücksrad", fr: "Roue de la Fortune" },
  "Aspectos": { en: "Aspects", es: "Aspectos", de: "Aspekte", fr: "Aspects" },
  "Trânsitos": { en: "Transits", es: "Tránsitos", de: "Transite", fr: "Transits" },
  "Sinastria": { en: "Synastry", es: "Sinastría", de: "Synastrie", fr: "Synastrie" },
  "Revolução Solar": { en: "Solar Return", es: "Revolución Solar", de: "Solar-Revolution", fr: "Révolution Solaire" },
  "Casas": { en: "Houses", es: "Casas", de: "Häuser", fr: "Maisons" },
  "Planetas": { en: "Planets", es: "Planetas", de: "Planeten", fr: "Planètes" },
  "Signos": { en: "Signs", es: "Signos", de: "Sternzeichen", fr: "Signes" },
  "Fogo": { en: "Fire", es: "Fuego", de: "Feuer", fr: "Feu" },
  "Terra": { en: "Earth", es: "Tierra", de: "Erde", fr: "Terre" },
  "Ar": { en: "Air", es: "Aire", de: "Luft", fr: "Air" },
  "Água": { en: "Water", es: "Agua", de: "Wasser", fr: "Eau" },
  "Cardinal": { en: "Cardinal", es: "Cardinal", de: "Kardinal", fr: "Cardinal" },
  "Fixo": { en: "Fixed", es: "Fijo", de: "Fix", fr: "Fixe" },
  "Mutável": { en: "Mutable", es: "Mutable", de: "Veränderlich", fr: "Mutable" },
  "Masculino / Yang": { en: "Masculine / Yang", es: "Masculino / Yang", de: "Männlich / Yang", fr: "Masculin / Yang" },
  "Feminino / Yin": { en: "Feminine / Yin", es: "Femenino / Yin", de: "Weiblich / Yin", fr: "Féminin / Yin" },
  "Harmonia": { en: "Harmony", es: "Armonía", de: "Harmonie", fr: "Harmonie" },
  "Tensão": { en: "Tension", es: "Tensión", de: "Spannung", fr: "Tension" },
  "Neutro": { en: "Neutral", es: "Neutro", de: "Neutral", fr: "Neutre" },
  "Conjunção": { en: "Conjunction", es: "Conjunción", de: "Konjunktion", fr: "Conjonction" },
  "Oposição": { en: "Opposition", es: "Oposición", de: "Opposition", fr: "Opposition" },
  "Trígono": { en: "Trine", es: "Trígono", de: "Trigon", fr: "Trigone" },
  "Quadratura": { en: "Square", es: "Cuadratura", de: "Quadrat", fr: "Carré" },
  "Sextil": { en: "Sextile", es: "Sextil", de: "Sextil", fr: "Sextile" },
  "Copas": { en: "Cups", es: "Copas", de: "Kelche", fr: "Coupes" },
  "Paus": { en: "Wands", es: "Bastos", de: "Stäbe", fr: "Bâtons" },
  "Espadas": { en: "Swords", es: "Espadas", de: "Schwerter", fr: "Épées" },
  "Ouros": { en: "Pentacles", es: "Oros", de: "Münzen", fr: "Deniers" },
  "Ás": { en: "Ace", es: "As", de: "Ass", fr: "As" },
  "Valete": { en: "Page", es: "Sota", de: "Bube", fr: "Valet" },
  "Cavaleiro": { en: "Knight", es: "Caballero", de: "Ritter", fr: "Cavalier" },
  "Rainha": { en: "Queen", es: "Reina", de: "Königin", fr: "Reine" },
  "Rei": { en: "King", es: "Rey", de: "König", fr: "Roi" },
  "Físico": { en: "Physical", es: "Físico", de: "Physisch", fr: "Physique" },
  "Emocional": { en: "Emotional", es: "Emocional", de: "Emotional", fr: "Émotionnel" },
  "Intelectual": { en: "Intellectual", es: "Intelectual", de: "Intellektuell", fr: "Intellectuel" },
  "Espiritual": { en: "Spiritual", es: "Espiritual", de: "Spirituell", fr: "Spirituel" },
  "Intuitivo": { en: "Intuitive", es: "Intuitivo", de: "Intuitiv", fr: "Intuitif" },
  "Estético": { en: "Aesthetic", es: "Estético", de: "Ästhetisch", fr: "Esthétique" },
  "Sensorial": { en: "Sensory", es: "Sensorial", de: "Sensorisch", fr: "Sensoriel" },
  "Hoje": { en: "Today", es: "Hoy", de: "Heute", fr: "Aujourd'hui" },
  "Ontem": { en: "Yesterday", es: "Ayer", de: "Gestern", fr: "Hier" },
  "Amanhã": { en: "Tomorrow", es: "Mañana", de: "Morgen", fr: "Demain" },
  "Semana": { en: "Week", es: "Semana", de: "Woche", fr: "Semaine" },
  "Mês": { en: "Month", es: "Mes", de: "Monat", fr: "Mois" },
  "Ano": { en: "Year", es: "Año", de: "Jahr", fr: "An" },
  "Dias": { en: "Days", es: "Días", de: "Tage", fr: "Jours" },
  "Horas": { en: "Hours", es: "Horas", de: "Stunden", fr: "Heures" },
  "Minutos": { en: "Minutes", es: "Minutos", de: "Minuten", fr: "Minutes" },
  "Segundos": { en: "Seconds", es: "Segundos", de: "Sekunden", fr: "Secondes" },
  "Próximo Domingo": { en: "Next Sunday", es: "Próximo Domingo", de: "Nächster Sonntag", fr: "Dimanche Prochain" },
  "às": { en: "at", es: "a las", de: "um", fr: "à" },
  "em": { en: "in", es: "en", de: "in", fr: "en" },
  "de": { en: "of", es: "de", de: "von", fr: "de" },
  "para": { en: "for", es: "para", de: "für", fr: "pour" },
  "com": { en: "with", es: "con", de: "mit", fr: "avec" },
  "sem": { en: "without", es: "sin", de: "ohne", fr: "sans" }
};

console.log('Loaded exact mappings.');
